# Generated by Django 3.2.11 on 2022-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0002_auto_20220312_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_limit', models.DateTimeField(null=True)),
                ('sectionId', models.IntegerField(default=1012, null=True)),
                ('superDivisionIds', models.TextField(null=True)),
                ('divisionIds', models.TextField(null=True)),
                ('maxQuestionCount', models.TextField(default=40, null=True)),
            ],
        ),
    ]
