# Generated by Django 3.2.11 on 2022-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0003_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
