# Generated by Django 3.2.11 on 2022-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0004_alter_sessions_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='maxQuestionCount',
            field=models.IntegerField(default=40, null=True),
        ),
    ]
