# Generated by Django 3.2.11 on 2022-03-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0006_sessions_questionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='questionList',
            new_name='questionIdList',
        ),
    ]
