# Generated by Django 3.2.11 on 2022-03-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0007_rename_questionlist_sessions_questionidlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='created_time',
            new_name='createdTime',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='time_limit',
            new_name='timeLimit',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='sectionId',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='superDivisionIds',
        ),
    ]
