# Generated by Django 3.2.11 on 2022-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0008_auto_20220312_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='timeLimit',
            field=models.IntegerField(null=True),
        ),
    ]
