# Generated by Django 3.2.11 on 2022-03-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapi', '0010_sessions_questionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='divisionIds',
            new_name='topicIds',
        ),
    ]
